# -*- coding: utf-8 -*-
"""
Workspace & State Health Validator (validate_state.py)
=========================================================
P0 健壮性：对工作区目录结构、JSON 状态 SSOT、economy_ledger.json 做确定性体检，
检查：缺文件、JSON 不可解析、台账不平衡、流水引用未声明资源池、伏笔/误会编号
重复、快照可读性等。供 `studio.py doctor` 调用。

状态 SSOT 以 JSON 为准；Markdown 视图仅检查是否存在。

Usage:
    python tools/validate_state.py
    python tools/validate_state.py -w novel_workspace --json
"""

import sys
import json
import argparse
from pathlib import Path

_tools_dir = Path(__file__).resolve().parent
if str(_tools_dir) not in sys.path:
    sys.path.insert(0, str(_tools_dir))

from novel_utils import resolve_workspace, reconfigure_utf8
import state_store as ss

reconfigure_utf8()

REQUIRED_DIRS = [
    "00_meta", "01_world", "02_characters", "02_characters/profiles",
    "03_outlines", "04_timeline_and_state",
    "05_manuscript/vol_01/raw_drafts", "05_manuscript/vol_01/finalized",
]
REQUIRED_FILES = [
    "00_meta/project_bible.md",
    "01_world/world_rules.md",
    "02_characters/character_index.md",
    # JSON SSOT
    "04_timeline_and_state/current_state.json",
    "04_timeline_and_state/timeline.json",
    "04_timeline_and_state/chekhov_guns.json",
    "04_timeline_and_state/misunderstandings.json",
    "04_timeline_and_state/character_growth_arcs.json",
    "04_timeline_and_state/economy_ledger.json",
]
# Markdown read-only views (soft requirement: regenerated by state_store)
MD_VIEWS = [
    "04_timeline_and_state/current_state.md",
    "04_timeline_and_state/timeline.md",
    "04_timeline_and_state/chekhov_guns.md",
    "04_timeline_and_state/misunderstandings.md",
    "04_timeline_and_state/character_growth_arcs.md",
]


def _load_json(p: Path):
    try:
        return json.loads(p.read_text(encoding="utf-8-sig")), None
    except Exception as e:
        return None, f"{p.name} 无法解析: {e}"


def _validate_ledger(state_dir: Path, errors: list, warnings: list):
    p = state_dir / "economy_ledger.json"
    if not p.exists():
        errors.append("缺少 economy_ledger.json")
        return
    data, err = _load_json(p)
    if err:
        errors.append(err)
        return
    pools = data.get("resource_pools")
    if pools is None:
        warnings.append("economy_ledger.json 无 resource_pools（单币种旧格式，建议迁移）")
        return
    running = {k: v.get("initial", 0) for k, v in pools.items()}
    for i, t in enumerate(data.get("transactions", []), 1):
        rk = t.get("resource")
        if rk is None:
            rk = next(iter(pools))
        if rk not in running:
            errors.append(
                f"账本流水 #{i} 引用未声明资源池 '{rk}'（章节 {t.get('chapter','?')}）")
            continue
        delta = t.get("delta")
        if delta is None:
            delta = t.get("inflow", 0) - t.get("outflow", 0)
        try:
            running[rk] += int(delta)
        except (TypeError, ValueError):
            errors.append(f"账本流水 #{i} delta 非数值: {delta!r}")
            continue
        if t.get("balance_after") is not None and t["balance_after"] != running[rk]:
            warnings.append(
                f"流水 #{i}（{t.get('chapter','?')}/{rk}）记录结余 {t['balance_after']} "
                f"与流水累计 {running[rk]} 不符")
    for k, v in pools.items():
        declared = v.get("current", v.get("initial", 0))
        if declared != running.get(k):
            errors.append(
                f"资源池【{v.get('name', k)}】声明余额 {declared} 与流水累计 {running.get(k)} 不平衡")


def _check_id_sequence(items: list, id_key: str, prefix: str, name: str,
                       errors: list):
    ids = []
    for it in items:
        val = str(it.get(id_key, ""))
        import re
        m = re.search(prefix + r"[-_]?(\d+)", val)
        if m:
            ids.append(int(m.group(1)))
    dup = {x for x in ids if ids.count(x) > 1}
    if dup:
        errors.append(f"{name} 存在重复编号: {sorted(dup)}")


def validate_workspace(workspace: Path):
    errors, warnings, ok_files = [], [], []

    for d in REQUIRED_DIRS:
        if not (workspace / d).is_dir():
            errors.append(f"缺少目录: {d}/")
    for f in REQUIRED_FILES:
        if (workspace / f).exists():
            ok_files.append(f)
        else:
            errors.append(f"缺少文件: {f}")

    state_dir = workspace / "04_timeline_and_state"

    # Markdown views: warn if missing (can be regenerated)
    for f in MD_VIEWS:
        if not (workspace / f).exists():
            warnings.append(f"缺少 Markdown 只读视图: {f}（可运行 sync 重新渲染）")

    # JSON parseability + id uniqueness
    for fname, key_in, id_key, prefix, label in [
        ("chekhov_guns.json", "guns", "id", "GUN", "伏笔台账"),
        ("misunderstandings.json", "misunderstandings", "id", "MIS", "误会台账"),
    ]:
        p = state_dir / fname
        if p.exists():
            data, err = _load_json(p)
            if err:
                errors.append(err)
            else:
                items = data.get(key_in, []) if isinstance(data, dict) else []
                _check_id_sequence(items, id_key, prefix, label, errors)

    # Other JSON state files parseability
    for fname in ("current_state.json", "timeline.json",
                  "character_growth_arcs.json"):
        p = state_dir / fname
        if p.exists():
            _, err = _load_json(p)
            if err:
                errors.append(err)

    # Economy ledger
    if (state_dir / "economy_ledger.json").exists():
        _validate_ledger(state_dir, errors, warnings)

    # Snapshots
    snap_dir = state_dir / "snapshots"
    if snap_dir.exists():
        for d in snap_dir.iterdir():
            if d.is_dir() and not any(d.glob("*.md")) and not any(d.glob("*.json")):
                warnings.append(f"快照 {d.name} 为空目录")

    status_str = "ERRORS" if errors else ("WARNINGS" if warnings else "HEALTHY")
    report = {
        "workspace": str(workspace),
        "status": status_str,
        "error_count": len(errors),
        "warning_count": len(warnings),
        "errors": errors,
        "warnings": warnings,
        "checked_files": ok_files,
    }
    return report


def main():
    parser = argparse.ArgumentParser(description="工作区与状态机健康自检 (doctor)")
    parser.add_argument("--workspace", "-w", type=str, default=None)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    ws = resolve_workspace(args.workspace)
    if not ws.exists():
        rep = {"status": "MISSING",
               "errors": [f"工作区不存在: {ws}（请先 studio.py init）"]}
        if args.json:
            print(json.dumps(rep, ensure_ascii=False, indent=2))
        else:
            print(f"❌ {rep['errors'][0]}")
        sys.exit(1)

    rep = validate_workspace(ws)
    if args.json:
        print(json.dumps(rep, ensure_ascii=False, indent=2))
    else:
        print("=" * 72)
        print(f" 🩺 [工作区健康自检] {ws.name}")
        print("=" * 72)
        for e in rep["errors"]:
            print(f"   ❌ {e}")
        for w in rep["warnings"]:
            print(f"   ⚠️ {w}")
        if not rep["errors"] and not rep["warnings"]:
            print("   ✅ 结构完整、台账平衡，工作区健康！")
        print("=" * 72)
        print(f" 结论: {rep['status']}（错误 {rep['error_count']} / 警告 {rep['warning_count']}）")
        print("=" * 72)
    sys.exit(1 if rep["errors"] else 0)


if __name__ == "__main__":
    main()
